defmodule Mix.Tasks.Lucidex.Install.Docs do
  @moduledoc false

  def short_doc, do: "Installs Lucidex into a Phoenix project"

  def example, do: "mix igniter.install lucidex"

  def long_doc do
    """
    #{short_doc()}

    ## Example

    ```sh
    #{example()}
    ```

    ## Changes

      * adds the `:lucidex` compiler after the default compilers in `mix.exs`
      * places `Lucidex.sprite_tag/0` at the top of `<body>` in the root layout
      * configures inline delivery in `config/dev.exs`
      * gitignores the generated sprite, `/priv/static/images/lucide.svg`
    """
  end
end

if Code.ensure_loaded?(Igniter) do
  defmodule Mix.Tasks.Lucidex.Install do
    @shortdoc "#{__MODULE__.Docs.short_doc()}"
    @moduledoc __MODULE__.Docs.long_doc()

    use Igniter.Mix.Task

    @sprite_tag "<%= Lucidex.sprite_tag() %>"
    @sprite_path "/priv/static/images/lucide.svg"

    @impl Igniter.Mix.Task
    def info(_argv, _composing_task) do
      %Igniter.Mix.Task.Info{
        group: :lucidex,
        example: __MODULE__.Docs.example(),
        schema: [],
        adds_deps: [],
        installs: [],
        composes: [],
        positional: [],
        defaults: [],
        aliases: [],
        required: []
      }
    end

    @impl Igniter.Mix.Task
    def igniter(igniter) do
      igniter
      |> add_compiler()
      |> add_sprite_tag()
      |> configure_dev()
      |> ignore_sprite()
      |> Igniter.add_notice(
        ~s(Lucidex is installed. Use icons with <Lucidex.icon name="house" />; misspelled names fail `mix compile`. Run `mix lucidex.download` to fetch newer Lucide icons.)
      )
    end

    defp add_compiler(igniter) do
      Igniter.Project.MixProject.update(igniter, :project, [:compilers], &compilers/1)
    end

    defp compilers(nil), do: {:ok, {:code, "Mix.compilers() ++ [:lucidex]"}}

    defp compilers(zipper) do
      code = Sourceror.to_string(zipper.node)

      cond do
        String.contains?(code, ":lucidex") -> {:ok, zipper}
        Igniter.Code.List.list?(zipper) -> Igniter.Code.List.append_new_to_list(zipper, :lucidex)
        # `++` is right-associative, so `:lucidex` stays last.
        true -> {:ok, {:code, code <> " ++ [:lucidex]"}}
      end
    end

    defp add_sprite_tag(igniter) do
      web_dir =
        igniter |> Igniter.Libs.Phoenix.web_module() |> inspect() |> Macro.underscore()

      path = "lib/#{web_dir}/components/layouts/root.html.heex"

      if Igniter.exists?(igniter, path) do
        Igniter.update_file(igniter, path, &insert_sprite_tag(&1, path))
      else
        Igniter.add_warning(
          igniter,
          "Could not find #{path}. Add `#{@sprite_tag}` at the top of <body> in your root layout."
        )
      end
    end

    defp insert_sprite_tag(source, path) do
      content = Rewrite.Source.get(source, :content)

      cond do
        String.contains?(content, "Lucidex.sprite_tag()") ->
          source

        match = Regex.run(~r/^([ \t]*)<body\b[^>]*>[^\n]*\n/m, content, return: :index) ->
          [{start, len}, {indent_start, indent_len}] = match
          indent = binary_part(content, indent_start, indent_len)
          {before, rest} = String.split_at(content, start + len)

          Rewrite.Source.update(
            source,
            :content,
            before <> indent <> "  " <> @sprite_tag <> "\n" <> rest
          )

        true ->
          {:warning,
           "Could not find a <body> tag in #{path}. Add `#{@sprite_tag}` at the top of <body> manually."}
      end
    end

    defp configure_dev(igniter) do
      app = Igniter.Project.Application.app_name(igniter)

      igniter
      |> Igniter.Project.Config.configure_new("dev.exs", :lucidex, [:delivery], :inline)
      |> Igniter.Project.Config.configure_new("dev.exs", :lucidex, [:otp_app], app)
    end

    defp ignore_sprite(igniter) do
      Igniter.create_or_update_file(igniter, ".gitignore", @sprite_path <> "\n", fn source ->
        content = Rewrite.Source.get(source, :content)

        ignored? =
          content
          |> String.split("\n")
          |> Enum.any?(&(String.trim(&1) in [@sprite_path, String.trim_leading(@sprite_path, "/")]))

        if ignored? do
          source
        else
          separator = if content == "" or String.ends_with?(content, "\n"), do: "", else: "\n"

          Rewrite.Source.update(
            source,
            :content,
            content <> separator <> "\n# Generated by the lucidex compiler\n" <> @sprite_path <> "\n"
          )
        end
      end)
    end
  end
else
  defmodule Mix.Tasks.Lucidex.Install do
    @shortdoc "#{__MODULE__.Docs.short_doc()} | Install `igniter` to use"
    @moduledoc __MODULE__.Docs.long_doc()

    use Mix.Task

    @impl Mix.Task
    def run(_argv) do
      Mix.shell().error("""
      The task 'lucidex.install' requires igniter. Please install igniter and try again.

      For more information, see: https://hexdocs.pm/igniter/readme.html#installation
      """)

      exit({:shutdown, 1})
    end
  end
end
